name: 'Cancel All Previous Workflow Runs'
description: 'A Github action that cancels all previous workflows for older commits in its branch (not workflow specific)'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'archive'  
  color: 'blue'
